#include "exception/get_task_error.h"

get_task_error::get_task_error() :
	std::exception() {}

get_task_error::~get_task_error() {}
